name: trauma-former
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - cudatoolkit=11.8
  - numpy=1.24
  - pandas=2.0
  - scipy=1.11
  - scikit-learn=1.3
  - matplotlib=3.7
  - seaborn=0.12
  - jupyter=1.0
  - pyyaml=6.0
  - tqdm=4.65
  - pip
  - pip:
    - redis==5.0.0
    - plotly==5.17.0
    - pytest==7.4.2